const fs = require('fs');
const path = require('path');
const { exec } = require('child_process');

// Load environment variables if running as standalone script
if (require.main === module) {
    require('dotenv').config({ path: path.join(__dirname, '../../.env') });
}

const SipTrunk = require('../../models/SipTrunk');

// Helper to get constants dynamically (ensures .env is respected)
const getConstants = () => ({
    ASTERISK_CONFIG_DIR: process.env.ASTERISK_CONFIG_DIR || '/etc/asterisk',
    IC_SIP_PORT: process.env.IC_SIP_PORT || '5090',
    ARI_USER: process.env.ASTERISK_ARI_USER || 'intellicall',
    ARI_PASSWORD: process.env.ASTERISK_ARI_PASSWORD || 'intellicall_ari_secret'
});

/**
 * Generate PJSIP config for all active SIP trunks
 */
async function generatePjsipConfig() {
    const trunks = await SipTrunk.find({ status: 'active' });

    let config = '; Auto-generated by IntelliCall AI — DO NOT EDIT MANUALLY\n';
    config += '; Regenerate via: node services/sip/asterisk-config.js\n\n';

    // Transport - create UDP, TCP and TLS transports
    const { IC_SIP_PORT } = getConstants();
    const basePort = parseInt(IC_SIP_PORT) || 5090;

    // Detect external IP for NAT traversal (critical for VPS / cloud hosting)
    const externalIp = process.env.EXTERNAL_IP || '';

    // UDP transport
    config += `[intellicall-transport-udp]\ntype=transport\nprotocol=udp\nbind=0.0.0.0:${basePort}\n`;
    if (externalIp) {
        config += `external_media_address=${externalIp}\n`;
        config += `external_signaling_address=${externalIp}\n`;
    }
    config += `local_net=10.0.0.0/8\nlocal_net=172.16.0.0/12\nlocal_net=192.168.0.0/16\n\n`;

    // TCP transport
    config += `[intellicall-transport-tcp]\ntype=transport\nprotocol=tcp\nbind=0.0.0.0:${basePort + 1}\n`;
    if (externalIp) {
        config += `external_media_address=${externalIp}\n`;
        config += `external_signaling_address=${externalIp}\n`;
    }
    config += `local_net=10.0.0.0/8\nlocal_net=172.16.0.0/12\nlocal_net=192.168.0.0/16\n\n`;

    // TLS transport (for providers requiring encrypted SIP signaling)
    const tlsCertFile = process.env.SIP_TLS_CERT || '/etc/asterisk/keys/asterisk.pem';
    const tlsKeyFile = process.env.SIP_TLS_KEY || '/etc/asterisk/keys/asterisk.key';
    const tlsCaFile = process.env.SIP_TLS_CA || '';
    config += `[intellicall-transport-tls]\ntype=transport\nprotocol=tls\nbind=0.0.0.0:${basePort + 2}\n`;
    config += `cert_file=${tlsCertFile}\npriv_key_file=${tlsKeyFile}\n`;
    if (tlsCaFile) config += `ca_list_file=${tlsCaFile}\n`;
    config += `method=tlsv1_2\n`;
    if (externalIp) {
        config += `external_media_address=${externalIp}\n`;
        config += `external_signaling_address=${externalIp}\n`;
    }
    config += `local_net=10.0.0.0/8\nlocal_net=172.16.0.0/12\nlocal_net=192.168.0.0/16\n\n`;

    // Codec name mapping: SIP standard names to Asterisk names
    const codecMap = {
        'pcmu': 'ulaw',
        'pcma': 'alaw',
        'g729': 'g729',
        'g722': 'g722',
        'opus': 'opus'
    };

    // Transport name mapping: match user selection from UI
    const transportMap = {
        'udp': 'intellicall-transport-udp',
        'tcp': 'intellicall-transport-tcp',
        'tls': 'intellicall-transport-tls'
    };

    for (const trunk of trunks) {
        const id = trunk._id.toString();
        const pw = trunk.password; // virtual getter auto-decrypts

        // Respect the user's transport selection from the UI
        const trunkTransport = (trunk.transport || 'udp').toLowerCase();
        const transportName = transportMap[trunkTransport] || 'intellicall-transport-udp';

        // Map SIP codec names to Asterisk codec names
        const codecs = (trunk.codecs || 'PCMU,PCMA').split(',')
            .map(c => c.trim().toLowerCase())
            .map(c => codecMap[c] || c);

        // Normalize caller ID to E.164 format (strip spaces/dashes, ensure + prefix for numbers)
        let callerId = (trunk.defaultCallerId || '').replace(/[\s\-()]/g, '');
        if (callerId && /^\d+$/.test(callerId)) callerId = `+${callerId}`;

        // Auth
        if (trunk.username) {
            config += `[trunk-${id}-auth]\ntype=auth\nauth_type=userpass\n`;
            config += `username=${trunk.username}\npassword=${pw}\n`;
            if (trunk.authRealm) config += `realm=${trunk.authRealm}\n`;
            config += '\n';
        }

        // AOR (address of record)
        // Use transport-aware contact URI
        const contactTransport = trunkTransport === 'tls' ? 'tls' : trunkTransport;
        config += `[trunk-${id}-aor]\ntype=aor\n`;
        config += `contact=sip:${trunk.host}:${trunk.port}\\;transport=${contactTransport}\n`;
        config += 'qualify_frequency=60\n\n';

        // Registration (only when credentials are provided)
        if (trunk.username) {
            config += `[trunk-${id}-reg]\ntype=registration\n`;
            config += `transport=${transportName}\n`;
            config += `outbound_auth=trunk-${id}-auth\n`;
            config += `server_uri=sip:${trunk.host}:${trunk.port}\\;transport=${contactTransport}\n`;
            config += `client_uri=sip:${trunk.username}@${trunk.host}\\;transport=${contactTransport}\n`;
            config += 'retry_interval=60\nexpiration=3600\n\n';
        }

        // Endpoint
        config += `[trunk-${id}]\ntype=endpoint\ntransport=${transportName}\n`;
        if (trunk.username) config += `outbound_auth=trunk-${id}-auth\n`;
        config += `aors=trunk-${id}-aor\ncontext=intellicall-inbound\n`;
        config += 'disallow=all\n';
        for (const codec of codecs) config += `allow=${codec}\n`;
        config += 'direct_media=no\nrtp_symmetric=yes\nforce_rport=yes\nrewrite_contact=yes\n';
        // DTMF: RFC 2833 is the most widely supported method
        config += 'dtmf_mode=rfc4733\n';
        if (callerId) config += `from_user=${callerId}\n`;
        // ICE/STUN not needed for server-side (Asterisk knows its own IP)
        config += 'ice_support=no\n';
        config += '\n';

        // Identify (match inbound calls from this trunk)
        config += `[trunk-${id}-identify]\ntype=identify\n`;
        config += `endpoint=trunk-${id}\nmatch=${trunk.host}\n\n`;
    }

    return config;
}

/**
 * Generate extensions.conf dialplan for inbound SIP routing
 */
function generateExtensionsConfig() {
    let config = '; Auto-generated by IntelliCall AI\n\n';
    config += '[intellicall-inbound]\n';
    config += '; Route ALL inbound SIP trunk calls to our Stasis ARI app\n';
    config += 'exten => _X.,1,NoOp(IntelliCall SIP inbound: ${EXTEN})\n';
    config += ' same => n,Answer()\n';
    config += ' same => n,Stasis(intellicall,inbound,${EXTEN})\n';
    config += ' same => n,Hangup()\n\n';
    config += 'exten => _+X.,1,NoOp(IntelliCall SIP inbound: ${EXTEN})\n';
    config += ' same => n,Answer()\n';
    config += ' same => n,Stasis(intellicall,inbound,${EXTEN})\n';
    config += ' same => n,Hangup()\n';
    return config;
}

/**
 * Generate ari.conf for ARI user
 */
function generateAriConfig() {
    const { ARI_USER, ARI_PASSWORD } = getConstants();
    return `; Auto-generated by IntelliCall AI\n[general]\nenabled=yes\npretty=yes\nallowed_origins=*\n\n[${ARI_USER}]\ntype=user\nread_only=no\npassword=${ARI_PASSWORD}\n`;
}

/**
 * Generate http.conf to enable ARI HTTP
 */
function generateHttpConfig() {
    return `; Auto-generated by IntelliCall AI\n[general]\nenabled=yes\nbindaddr=127.0.0.1\nbindport=8088\n`;
}

/**
 * Helper to ensure a main Asterisk config file #includes our custom IC configs
 * For pjsip.conf, we prepend the include at the TOP of the file to ensure proper parsing
 * CRITICAL: Must ensure only ONE include line exists (duplicates cause sorcery errors)
 */
function ensureLinked(mainFileName, includeFileName) {
    const { ASTERISK_CONFIG_DIR } = getConstants();
    const mainFilePath = path.join(ASTERISK_CONFIG_DIR, mainFileName);
    const includeLine = `#include "intellicall/${includeFileName}"`;

    try {
        if (!fs.existsSync(mainFilePath)) {
            // If the main file doesn't exist, we can't link to it. 
            // This is common if the user hasn't installed Asterisk yet.
            return { success: false, reason: 'not_found' };
        }

        let content = fs.readFileSync(mainFilePath, 'utf8');
        
        // Count existing includes to detect duplicates
        const includeRegex = new RegExp(includeLine.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'g');
        const matches = content.match(includeRegex) || [];
        
        if (matches.length === 1) {
            // Already has exactly one include - check if it's at the top for pjsip.conf
            if (mainFileName === 'pjsip.conf' && !content.startsWith(includeLine)) {
                // Move it to top
                content = content.replace(includeRegex, '');
                content = `${includeLine}\n${content}`;
                fs.writeFileSync(mainFilePath, content);
                console.log(`✅ Moved ${includeFileName} to top of ${mainFileName}`);
                return { success: true, reason: 'moved_to_top' };
            }
            return { success: true, reason: 'already_linked' };
        }
        
        if (matches.length > 1) {
            // Remove ALL duplicates and add just one at the correct location
            content = content.replace(includeRegex, '');
            console.log(`⚠️  Removed ${matches.length} duplicate includes from ${mainFileName}`);
        }
        
        // Clean up any extra newlines from removal
        content = content.replace(/^\n+/, '');

        // For pjsip.conf, prepend at the beginning to ensure proper parsing
        // Other files can be appended at the end
        if (mainFileName === 'pjsip.conf') {
            content = `${includeLine}\n\n${content}`;
            fs.writeFileSync(mainFilePath, content);
            console.log(`✅ Prepended ${includeFileName} to ${mainFileName}`);
        } else {
            fs.appendFileSync(mainFilePath, `\n${includeLine}\n`);
            console.log(`✅ Linked ${includeFileName} to ${mainFileName}`);
        }
        return { success: true, reason: 'linked_now' };
    } catch (err) {
        if (err.code === 'EACCES') {
            return { success: false, reason: 'permission_denied' };
        }
        return { success: false, reason: err.message };
    }
}

/**
 * Write all config files and reload Asterisk
 */
async function writeAndReload() {
    const { ASTERISK_CONFIG_DIR } = getConstants();
    const INTELLICALL_DIR = path.join(ASTERISK_CONFIG_DIR, 'intellicall');

    if (!fs.existsSync(INTELLICALL_DIR)) {
        try {
            fs.mkdirSync(INTELLICALL_DIR, { recursive: true });
        } catch (err) {
            console.error(`❌ Failed to create config directory: ${err.message}`);
            return { success: false, message: 'Permission denied to create Asterisk config folder' };
        }
    }

    // 1. Generate and write the custom IC config files
    const pjsip = await generatePjsipConfig();
    fs.writeFileSync(path.join(INTELLICALL_DIR, 'pjsip_intellicall.conf'), pjsip);
    fs.writeFileSync(path.join(INTELLICALL_DIR, 'extensions_intellicall.conf'), generateExtensionsConfig());
    fs.writeFileSync(path.join(INTELLICALL_DIR, 'ari_intellicall.conf'), generateAriConfig());
    fs.writeFileSync(path.join(INTELLICALL_DIR, 'http_intellicall.conf'), generateHttpConfig());

    // 2. Try to "Auto-Link" them to main Asterisk configs (The "One-Click" magic)
    const links = [
        ensureLinked('pjsip.conf', 'pjsip_intellicall.conf'),
        ensureLinked('extensions.conf', 'extensions_intellicall.conf'),
        ensureLinked('ari.conf', 'ari_intellicall.conf'),
        ensureLinked('http.conf', 'http_intellicall.conf')
    ];

    const allLinked = links.every(l => l.success || l.reason === 'already_linked');
    const somePermissionDenied = links.some(l => l.reason === 'permission_denied');

    console.log(`✅ Asterisk configs written to: ${INTELLICALL_DIR}`);

    // Helper: try command, fallback to sudo if permission denied
    const tryExec = (cmd) => new Promise((resolve) => {
        exec(cmd, (err, stdout, stderr) => {
            if (err) {
                // Try with sudo
                exec(`sudo ${cmd}`, (err2, stdout2, stderr2) => {
                    if (err2) {
                        console.warn(`⚠️  "${cmd}" failed (even with sudo):`, err2.message);
                        resolve(false);
                    } else {
                        console.log(`✅ "${cmd}" succeeded (via sudo)`);
                        resolve(true);
                    }
                });
            } else {
                console.log(`✅ "${cmd}" succeeded`);
                resolve(true);
            }
        });
    });

    // 3. Attempt reload — MUST reload both dialplan AND PJSIP
    // Use 'pjsip reload' to properly reload endpoints/aors/auth from config files
    // 'module reload res_pjsip.so' only reloads the module, not the sorcery configuration
    const dialplanOk = await tryExec('asterisk -rx "dialplan reload"');
    const pjsipOk = await tryExec('asterisk -rx "pjsip reload"');
    // Also reload outbound registration to pick up any new registrations
    await tryExec('asterisk -rx "module reload res_pjsip_outbound_registration.so"');

    if (pjsipOk) {
        return {
            success: true, reloaded: true, linked: allLinked,
            message: 'Asterisk configuration successfully updated and reloaded.'
        };
    } else {
        return {
            success: true, reloaded: false, linked: allLinked,
            message: somePermissionDenied
                ? 'Configs saved, but permission denied to link/reload. Run: sudo asterisk -rx "pjsip reload"'
                : 'Configs saved, but Asterisk PJSIP reload failed. Is Asterisk running?'
        };
    }
}

module.exports = { generatePjsipConfig, generateExtensionsConfig, writeAndReload };

// Allow running as standalone script: node services/sip/asterisk-config.js
if (require.main === module) {
    require('dotenv').config({ path: path.join(__dirname, '../../.env') });
    const mongoose = require('mongoose');
    mongoose.connect(process.env.MONGODB_URI).then(async () => {
        const result = await writeAndReload();
        console.log('Result:', result);
        process.exit(0);
    }).catch(err => { console.error(err); process.exit(1); });
}
